spring:
  profiles:
    include: "secret"
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG